<!DOCTYPE html>
		<html lang="fr">
			<head>
				<meta charset="utf-8">
					<title>Partage de compétences Toulousain</title>
					<link rel="stylesheet" type="text/css" href="config/modules/bootstrap4/css/bootstrap.css">
					<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
					<link rel="stylesheet" type="text/css" href="./css/thecascade.css">
			</head>
			<body>

				<div id="pagecontent" class="pre-scrollable">

				
  					<div class="container">
    					<a href="index_test.php" id="logonavbar">
    						<div class="page-header"><h1 id="banner-title">Plateforme Toulousaine de Partage de Compétences</h1>
    						</div>
    					</a>
  					</div>
				

					<div class="connexion">