
						</div>
			            <div id="footercontent" class="fixed-bottom">
	            			
	                    	<p id="contactus"> Contact : partage.toulousain@andresdelgado.fr </p>
	                		
	        			</div>


					<script type="text/javascript" src="config/modules/bootstrap4/js/bootstrap.js"></script>
					<script type="text/javascript" src="config/modules/jquery/jquery-3.3.1.min.js"></script>
					
			</body>
		</html>