
		    		    
   			<div id="login-box" class="login-popup">
      			<form method="post" class="signin" action="connexion.php">
                <fieldset class="textbox">
	                <label class="username">
		                <span>Identifiant</span>
		                <input id="username" class="form-control" name="username" value="" type="text" autocomplete="on" placeholder="identifiant">
	                </label>
	                
	                <label class="password">
		                <span>Mot de Passe</span>
		                <input id="password" class="form-control" name="password" value="" type="password" placeholder="mot de passe">
	                </label>
                
                	<button class="btn btn-default" type="submit">Se Connecter</button>
            	</fieldset>
      			</form>
			</div>;

			    <div id="register-box" class="register-popup">
					<p><i>Nouvel arrivant?</i></p>
					<form class="signup" action="register.php">
						<button class="btn btn-default" type="submit">Créer un compte</button>
					</form>
				</div>