<script type="text/javascript" src="functions.js"></script>
<script type="text/javascript">
		var deja_choisi_moi = false;
		var match = false;
		var id_cp_m = "";

		function placer_icones(crushed_d){
			var depend_m = <?php 
				include_once './queries/construction_calendrier.php';
				echo $dependant_meteo;
			?>;

			var tms_list = [];
			for (var tms in crushed_d){
				
				if (tms != 'cmd'){
					tms_list.push();
					var creneau = crushed_d[tms].dt;

					//oui ok bon c'est un peu pipé

					try{

						var liste_h = ["09","12","15"];

						for (var i=0;i<3;i++){

							if ((crushed_d[tms].heures[liste_h[i]].id != "800") && (depend_m == 1)){
								$($("#"+creneau).parent().find('.meteo_icon')[i]).parent().attr('bgcolor','#FF8080');
							}else{
								$($("#"+creneau).parent().find('.meteo_icon')[i]).parent().on('click',function(e){

									if (deja_choisi_moi){
										alert("Vous avez déjà choisi un créneau d'échange de compétences");
										
									}else{
										if (typeof $(this).attr('bgcolor') === 'undefined'){
											$(this).attr('bgcolor',"#BACCFF")
										}else if ($(this).attr('bgcolor') === "#BACCFF"){
											$(this).attr('bgcolor','#FFFFFF');
										}else{
											$(this).attr('bgcolor',"#BACCFF");
										}
										
										var creneau_j = $(this).parent().find(".timestamp_f")[0].id;

										var mon_id = "<?php echo $_COOKIE["session"]; ?>";
										var c_choisi = $(this).attr('id');
										var d_creneau = $(this).html();
										d_creneau = d_creneau.split(" ");

										var choisirc = {
											"cmd"      		: "creneau_c",
											"data" 	   		: mon_id,
											"c_choisi" 		: c_choisi,
											"data_creneau"	: d_creneau[0],
											"id_creneau"	: creneau_j
										};

										send_json(cx,choisirc);
										deja_choisi_moi = true;
									}

								});
							}
							$($("#"+creneau).parent().find('.meteo_icon')[0]).html("<img src='"+crushed_d[tms].heures["09"].icon+"'>");

							$($("#"+creneau).parent().find('.meteo_icon')[1]).html("<img src='"+crushed_d[tms].heures["12"].icon+"'>");
							$($("#"+creneau).parent().find('.meteo_icon')[2]).html("<img src='"+crushed_d[tms].heures["15"].icon+"'>");
						}		
					}catch(ex){
						console.log(creneau + ex);
					}
				}
			}
			
		}

 		var host = "<?php echo WS_HOST; ?>";

		try{
			var cx = new WebSocket(host);

			console.log(cx.readyState);

			var cmd_users = {
				"cmd" : "users"
			};

			cx.onopen = function(msg){
				send_json(this,cmd_users);
				$('#status_ws').html(service_status(this.readyState));

				var cmdMeteo = {
					"cmd" : "meteo_f",
					"city" : "Toulouse"
				};

				try{
					send_json(this,cmdMeteo);
				}catch(ex){
					console.log(ex);
				}
			};

			cx.onmessage = function(msg){
				var data = JSON.parse(msg.data);

				if (data.cmd == 'users'){
					gminfo('Il y a ' + data.nb_users + ' usager(s) connectés sur la plateforme');
				}else if(data.cmd == 'meteo_f'){
					console.log(data);
					placer_icones(data);

				}else if(data.cmd == 'creneau_c'){
					alert(data.data + " vient de choisir le créneau suivant : " + " à " 
						+ data.data_creneau + " le " + data.id_creneau);
					$('#' + data.c_choisi).attr('bgcolor',"#BACCFF");
				}

				//$('#texto').append(JSON.parse(msg.data)) ;
			};

			cx.onclose = function(msg){
				service_status(this.readyState);
			};
		}catch(ex){
			console.log(ex);
		}
</script>